version: "3.9"

services:
  chromadb:
    image: server
    container_name: chromadb_container
    build:
      context: ./chromadb
      dockerfile: Dockerfile
    volumes:
      - chroma-data:/chroma/chroma
    command: "--workers 1 --host 0.0.0.0 --port 8000 --proxy-headers --log-config ./log_config.yml --timeout-keep-alive 30"
    environment:
      - IS_PERSISTENT=TRUE
      - CHROMA_SERVER_AUTH_PROVIDER=${CHROMA_SERVER_AUTH_PROVIDER}
      - CHROMA_SERVER_AUTH_CREDENTIALS_FILE=${CHROMA_SERVER_AUTH_CREDENTIALS_FILE}
      - CHROMA_SERVER_AUTH_CREDENTIALS=${CHROMA_SERVER_AUTH_CREDENTIALS}
      - CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER=${CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER}
      - CHROMA_SERVER_AUTH_TOKEN_TRANSPORT_HEADER=${CHROMA_SERVER_AUTH_TOKEN_TRANSPORT_HEADER}
      - PERSIST_DIRECTORY=${PERSIST_DIRECTORY:-/chroma/chroma}
      - CHROMA_OTEL_EXPORTER_ENDPOINT=${CHROMA_OTEL_EXPORTER_ENDPOINT}
      - CHROMA_OTEL_EXPORTER_HEADERS=${CHROMA_OTEL_EXPORTER_HEADERS}
      - CHROMA_OTEL_SERVICE_NAME=${CHROMA_OTEL_SERVICE_NAME}
      - CHROMA_OTEL_GRANULARITY=${CHROMA_OTEL_GRANULARITY}
      - CHROMA_SERVER_NOFILE=${CHROMA_SERVER_NOFILE}
    restart: unless-stopped
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - net
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
      - path.repo=/usr/share/elasticsearch/snapshots
    ports:
      - "9200:9200"
    volumes:
      - $HOME/esdata1:/usr/share/elasticsearch/data
      - $HOME/es_snapshots:/usr/share/elasticsearch/snapshots
    networks:
      - net
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - net
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      XPACK_SECURITY_ENABLED: "false"
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - $HOME/redis/data:/data
      - $HOME/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - $HOME/redis/users.acl:/usr/local/etc/redis/users.acl
    command:
      [
        "redis-server",
        "/usr/local/etc/redis/redis.conf",
        "--requirepass",
        "my-password",
      ]
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
    networks:
      - net
  # Introducing langfuse
  langfuse:
    image: langfuse/langfuse:latest
    container_name: langfuse
    environment:
      DATABASE_URL: postgres://langfuse_user:password@postgres:5432/langfuse_db
      PORT: 3000
      NEXTAUTH_SECRET: +SC0UIGVT+U8xwXf780oB26nqL8xRSaHhBU6zcFdvp8=
      NEXTAUTH_URL: http://localhost:3000
      SALT: 3466e43428669a0feb2ee89ff49917dd
      ENCRYPTION_KEY: 32ecf4128dd9dbfad3a3c6f9b655c8d3b306aeb0c938f6c04e374faa75bee2ca
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: always
    networks:
      - net
  # Langfuse depends on postgres
  postgres:
    image: postgres:13
    container_name: langfuse_postgres
    environment:
      POSTGRES_DB: langfuse_db
      POSTGRES_USER: langfuse_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - net
volumes:
  chroma-data:
    driver: local
  postgres_data:

networks:
  net:
    driver: bridge