name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Digital Ocean
        run: |
          ssh -v -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP_ADDRESS }} << 'EOF'
            export HUGGING_FACE_API_KEY=${{ secrets.HUGGING_FACE_API_KEY }}
            export NEO4J_DATABASE=${{ secrets.NEO4J_DATABASE }}
            export NEO4J_PASSWORD=${{ secrets.NEO4J_PASSWORD }}
            export NEO4J_URL=${{ secrets.NEO4J_URL }}
            export NEO4J_USERNAME=${{ secrets.NEO4J_USERNAME }}
            if [ ! -d "/home/auravana/app" ]; then
              # Clone the repository if the directory doesn't exist
              git clone https://github.com/polux0/knowledge-graph-llama-index /home/auravana/app
            else
              # Pull the latest changes if the repository is already cloned
              cd /home/auravana/app
              git pull
            fi
            cd /home/auravana/app
            docker-compose up -d
          EOF